"""One narrowly-scoped, human-approved privileged NixOS diagnostic.

The tool has no arguments.  Its pre-tool hook always enters Hermes' native
human approval flow; the rule key is bound to the individual tool-call ID, so
session/permanent approval choices cannot silently authorize a later call.

The handler can only start one PolicyKit-authorized, root-owned systemd unit.
It cannot execute an arbitrary command or select a different unit.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any

_TOOL_NAME = "nixos_update_diagnostics"
_UNIT = "hermes-nixos-update-diagnostics.service"
_SYSTEMCTL = "/run/current-system/sw/bin/systemctl"
_REPORT = Path("/run/hermes-privileged-diagnostics/nixos-update-journal.txt")
_MAX_REPORT_CHARS = 24_000

_SCHEMA = {
    "name": _TOOL_NAME,
    "description": (
        "Request one-time user approval, then retrieve the root-readable journal "
        "for the most recent NixOS automatic-update runs. This tool accepts no "
        "arguments and cannot execute arbitrary commands."
    ),
    "parameters": {
        "type": "object",
        "properties": {},
        "additionalProperties": False,
    },
}


def _handle_diagnostics(params: dict[str, Any], **kwargs: Any) -> str:
    """Start the single fixed root-owned report unit and return its report."""
    del kwargs
    if params:
        return json.dumps({"success": False, "error": "this tool accepts no parameters"})
    try:
        completed = subprocess.run(
            (_SYSTEMCTL, "start", _UNIT),
            check=False,
            capture_output=True,
            text=True,
            timeout=45,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return json.dumps({"success": False, "error": f"could not start diagnostic unit: {exc}"})

    if completed.returncode != 0:
        detail = (completed.stderr or completed.stdout or "systemctl failed").strip()
        return json.dumps({"success": False, "error": detail[:2_000]})

    try:
        report = _REPORT.read_text(encoding="utf-8")
    except OSError as exc:
        return json.dumps({"success": False, "error": f"diagnostic report unavailable: {exc}"})

    truncated = len(report) > _MAX_REPORT_CHARS
    return json.dumps(
        {
            "success": True,
            "unit": _UNIT,
            "report": report[:_MAX_REPORT_CHARS],
            "truncated": truncated,
            "note": "The report is generated by a fixed root-owned systemd unit.",
        },
        ensure_ascii=False,
    )


def _require_individual_approval(
    *, tool_name: str, tool_call_id: str = "", **kwargs: Any
) -> dict[str, str] | None:
    """Force the native Telegram approval gate for every tool invocation."""
    del kwargs
    if tool_name != _TOOL_NAME:
        return None
    call_key = tool_call_id or "missing-call-id"
    return {
        "action": "approve",
        "rule_key": f"privileged-nixos-diagnostics:{call_key}",
        "message": (
            "Root-owned diagnostic requested. Exact action: "
            f"`systemctl start {_UNIT}`. The unit may only read the journal for "
            "`nixos-update.service` and publish a bounded report; it accepts no "
            "command, unit, path, or other parameter. Approve this one invocation only."
        ),
    }


def register(ctx: Any) -> None:
    ctx.register_tool(
        name=_TOOL_NAME,
        toolset="privileged_nixos_diagnostics",
        schema=_SCHEMA,
        handler=_handle_diagnostics,
        description=_SCHEMA["description"],
        emoji="🔐",
    )
    ctx.register_hook("pre_tool_call", _require_individual_approval)
